name: Build Website
on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build Website
    #    runs-on: ubuntu-20.04
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
        id: go

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.81.0"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      
      - name: Create build folder
        run:  mkdir cvedb-repo

      - name: Checkout public vuln-list-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/vuln-list
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/vuln-list

      - name: Checkout public kube-hunter-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/kube-hunter
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/kube-hunter-repo

      - name: Checkout public cloud-security-remediation-guides-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/cloud-security-remediation-guides
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/remediations-repo

      - name: Checkout public tracker-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/tracker
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/tracker-repo

      - name: Checkout public cloudsploit-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/cloudsploit
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/cloudsploit-repo

      - name: Checkout public defsec-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/defsec
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/defsec-repo

      - name: Checkout public kube-bench-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/kube-bench
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/kube-bench-repo

      - name: Checkout private chain-bench-repo
        uses: actions/checkout@v4
        with:
          repository: khulnasoft-lab/oss-chain-bench
          token: ${{ secrets.ORG_REPO_TOKEN }}
          path: cvedb-repo/chain-bench-repo

      - name: Build generator
        run: make md-clean md-build

      - name: Sync cvedb-repo with latest changes from generator
        run: make sync-all

      - name: Build and Generate Markdown pages
        run: make md-generate

      - name: Generate Hugo website
        run: make hugo-generate

      - name: Copy assets
        run: make copy-assets

      - name: Deploy Search Index to MeiliSearch Instance
        run: |
          cd cvedb-repo
          curl -H 'Content-Type: application/json' -H 'X-Meili-API-Key: ${{ secrets.SEARCHAPITOKEN }}' -X POST ${{ secrets.SEARCHAPIHOST }}/indexes/cvedb/documents --data @docs/searchindex.json

      - name: Install AWS CLI
        run: pip3 install awscli

      - name: Sync changes to the bucket
        run: aws s3 sync --no-progress --only-show-errors --size-only cvedb-repo/docs ${{ secrets.PROD_AVD_BUCKET }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AVD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AVD_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
